version: 0.0
os: linux
files:
  - source: /
    destination: /
hooks:
  AfterInstall:
    - location: aws-scripts/npm-install.sh
      runas: root
      timeout: 3000
  ApplicationStart:
    - location: aws-scripts/npm-start.sh
      runas: root
      timeout: 3000
