version: 0.0
os: linux
files:
    - source: /
      destination: /apps/react-tutorial-timers
hooks:
#  ApplicationStop:
#    - location: public/index.html
#      timeout: 180
  BeforeInstall:
    - location: public/index.html
      timeout: 180
  AfterInstall:
    - location: public/index.html
      timeout: 180
  ApplicationStart:
    - location: public/index.html
      timeout: 180
  ValidateService:
    - location: public/index.html
      timeout: 180
